import React from 'react';

import { Button, Hives, NextImage } from '@/components';

import exclamationSvg from '~/images/bts-factory/exclamation.png';

export default function MarketPlace() {
  return (
    <main>
      <section className="flex flex-col gap-28 bg-gray-400 pb-20">
        <Hives className="flex flex-col items-center gap-10 px-4  pt-40 md:flex-row md:justify-around md:px-11">
          <div className="grid">
            <h1 className="z-10 text-center text-3xl uppercase leading-normal  text-gray-400 md:text-[60px]">
              Marketplace
            </h1>
            <div className="mb-32 mt-5 h-[2px] w-full bg-gradient-to-r from-fuchsia-400 to-transparent"></div>
          </div>
        </Hives>
        <div className="container mx-auto grid grid-cols-1 gap-8 px-8 text-base leading-10 md:grid-cols-1 md:px-48 md:leading-6">
          Our platform provides a unique opportunity for both buyers and sellers
          in the Alvara community. The BTS Marketplace is where BTS creators can
          list their ERC-BTS tokens for auction.
          <br />
          <br /> Within our ERC-BTS Marketplace, creators can list their tokens
          for sale, presenting buyers the chance to receive management rights
          and a revenue stream generated by the BTS token. Additionally, holders
          of ERC-BTS tokens can receive a percentage of trading fees generated
          by their fund&apos;s BTS LP tokens when they are listed and traded on
          the HiveX.
          <br />
          <br /> Our marketplace provides clear and comprehensive information
          about each fund listed for sale. Buyers can easily view the
          profit/loss, decentralised (DAO) status, underlying assets, and
          management annual revenue stream for each fund. <br />
          <br />
          Sellers have full control over their auction listings, including
          setting a starting price, reserve price, and &quot;buy-it-now&quot;
          price. If buyers would like to make an offer lower than the
          &quot;buy-it-now&quot; price, they can use the
          &quot;make-an-offer&quot; option. Sellers can also add a blurb to
          describe their fund and provide additional information to attract
          potential buyers.
          <br />
          <br /> All transactions on the ERC-BTS Marketplace are final and
          settlement occurs on-chain to ensure a secure, efficient process.
          <br />
          <br /> You have the opportunity to participate in the BTS Marketplace
          and be a part of a growing, vibrant BTS community. List your ERC-BTS
          token today, or browse our selection of funds available for purchase.{' '}
          <br />
          <br />
          Don’t miss out.
        </div>
        <div className="hidden h-[1085px] w-full bg-[url('/images/market/back.svg')] bg-cover bg-center bg-no-repeat md:block"></div>
        <div className="block h-[1800px] w-full bg-[url('/images/market/mobile-back.svg')] bg-cover bg-center bg-no-repeat md:hidden">
          <div className=" group relative mt-[1400px] flex h-8 w-full place-content-center   bg-center bg-no-repeat ">
            <Button className=" place-self-center bg-none px-0">
              <NextImage
                className="m-auto "
                width={30}
                height={30}
                src={exclamationSvg}
                alt="exclamation"
              />
            </Button>
            <span
              className="absolute left-1/2 my-4 hidden w-72  translate-y-10 -translate-x-1/2 rounded-md  border-2 border-[#8A15D5] 
    bg-[#1C043C] px-1 text-center text-sm text-white transition-opacity group-hover:block"
            >
              The NFT holds the rights for proposals regarding the fund and
              generates management fee for the fund manager.
            </span>
          </div>
        </div>
      </section>
    </main>
  );
}
