/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace AlvrTokenSale {
  export type InvestmentsStruct = {
    investor: PromiseOrValue<string>;
    amounts: PromiseOrValue<BigNumberish>[];
    tokens: PromiseOrValue<BigNumberish>[];
  };

  export type InvestmentsStructOutput = [string, BigNumber[], BigNumber[]] & {
    investor: string;
    amounts: BigNumber[];
    tokens: BigNumber[];
  };
}

export interface AlvrTokenSaleInterface extends utils.Interface {
  functions: {
    "addVest(uint256[],uint256[],uint8,bytes32,bytes32)": FunctionFragment;
    "allowedPercentage()": FunctionFragment;
    "alvara()": FunctionFragment;
    "blockUsers(address[])": FunctionFragment;
    "claim()": FunctionFragment;
    "claimAdmin(address)": FunctionFragment;
    "claimable()": FunctionFragment;
    "claimed(address,uint256)": FunctionFragment;
    "fullPercent()": FunctionFragment;
    "getAllInvestors()": FunctionFragment;
    "investorCnt()": FunctionFragment;
    "investors(uint256)": FunctionFragment;
    "isBlocked(address)": FunctionFragment;
    "maximumTokens(uint256)": FunctionFragment;
    "minimumTokens(uint256)": FunctionFragment;
    "nonce(address)": FunctionFragment;
    "optionCnt()": FunctionFragment;
    "owner()": FunctionFragment;
    "pauseSale()": FunctionFragment;
    "paused()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "replaceUsers(address[],address[])": FunctionFragment;
    "schedules(uint256,uint256)": FunctionFragment;
    "setAllowedPercentage(uint256)": FunctionFragment;
    "setAlvara(address)": FunctionFragment;
    "setClaimable()": FunctionFragment;
    "setOptionCnt(uint256)": FunctionFragment;
    "setOptionMaxAmount(uint256,uint256)": FunctionFragment;
    "setOptionMinAmount(uint256,uint256)": FunctionFragment;
    "setOptionRange(uint256,uint256,uint256)": FunctionFragment;
    "setSchedule(uint256,uint256[])": FunctionFragment;
    "setTge(uint256)": FunctionFragment;
    "setTreasuryWallet(address)": FunctionFragment;
    "setTxSigner(address)": FunctionFragment;
    "setUnclaimable()": FunctionFragment;
    "tge()": FunctionFragment;
    "timeMonth()": FunctionFragment;
    "tokens(address,uint256)": FunctionFragment;
    "totalTokens()": FunctionFragment;
    "totalVests()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "treasuryWallet()": FunctionFragment;
    "txSigner()": FunctionFragment;
    "unblockUsers(address[])": FunctionFragment;
    "unclaimed(address)": FunctionFragment;
    "unpauseSale()": FunctionFragment;
    "vests(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addVest"
      | "allowedPercentage"
      | "alvara"
      | "blockUsers"
      | "claim"
      | "claimAdmin"
      | "claimable"
      | "claimed"
      | "fullPercent"
      | "getAllInvestors"
      | "investorCnt"
      | "investors"
      | "isBlocked"
      | "maximumTokens"
      | "minimumTokens"
      | "nonce"
      | "optionCnt"
      | "owner"
      | "pauseSale"
      | "paused"
      | "renounceOwnership"
      | "replaceUsers"
      | "schedules"
      | "setAllowedPercentage"
      | "setAlvara"
      | "setClaimable"
      | "setOptionCnt"
      | "setOptionMaxAmount"
      | "setOptionMinAmount"
      | "setOptionRange"
      | "setSchedule"
      | "setTge"
      | "setTreasuryWallet"
      | "setTxSigner"
      | "setUnclaimable"
      | "tge"
      | "timeMonth"
      | "tokens"
      | "totalTokens"
      | "totalVests"
      | "transferOwnership"
      | "treasuryWallet"
      | "txSigner"
      | "unblockUsers"
      | "unclaimed"
      | "unpauseSale"
      | "vests"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addVest",
    values: [
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "alvara", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "blockUsers",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "claimable", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "fullPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllInvestors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "investorCnt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "investors",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlocked",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "maximumTokens",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "minimumTokens",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "nonce",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "optionCnt", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pauseSale", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "replaceUsers",
    values: [PromiseOrValue<string>[], PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "schedules",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedPercentage",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAlvara",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOptionCnt",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOptionMaxAmount",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOptionMinAmount",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOptionRange",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setSchedule",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setTge",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryWallet",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTxSigner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setUnclaimable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tge", values?: undefined): string;
  encodeFunctionData(functionFragment: "timeMonth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryWallet",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "txSigner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unblockUsers",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "unclaimed",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vests",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "addVest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowedPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "alvara", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "blockUsers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fullPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investorCnt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "investors", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isBlocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maximumTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "optionCnt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pauseSale", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replaceUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "schedules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAlvara", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOptionCnt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOptionMaxAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOptionMinAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOptionRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTxSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUnclaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timeMonth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalVests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "txSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unblockUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unclaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unpauseSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vests", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface AlvrTokenSale extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AlvrTokenSaleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addVest(
      amounts_: PromiseOrValue<BigNumberish>[],
      tokens_: PromiseOrValue<BigNumberish>[],
      v_: PromiseOrValue<BigNumberish>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    allowedPercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    alvara(overrides?: CallOverrides): Promise<[string]>;

    blockUsers(
      users_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimAdmin(
      token_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimable(overrides?: CallOverrides): Promise<[boolean]>;

    claimed(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    fullPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    getAllInvestors(
      overrides?: CallOverrides
    ): Promise<[AlvrTokenSale.InvestmentsStructOutput[]]>;

    investorCnt(overrides?: CallOverrides): Promise<[BigNumber]>;

    investors(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isBlocked(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    maximumTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    minimumTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    nonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    optionCnt(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pauseSale(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    replaceUsers(
      oldUsers_: PromiseOrValue<string>[],
      newUsers_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    schedules(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setAllowedPercentage(
      allowedPercentage_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAlvara(
      alvara_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setClaimable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOptionCnt(
      optionCnt_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOptionMaxAmount(
      option: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOptionMinAmount(
      option: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOptionRange(
      option_: PromiseOrValue<BigNumberish>,
      minimum_: PromiseOrValue<BigNumberish>,
      maximum_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setSchedule(
      option_: PromiseOrValue<BigNumberish>,
      releases_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTge(
      tge_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTreasuryWallet(
      treasuryWallet_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTxSigner(
      txSigner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setUnclaimable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tge(overrides?: CallOverrides): Promise<[BigNumber]>;

    timeMonth(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokens(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalVests(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    treasuryWallet(overrides?: CallOverrides): Promise<[string]>;

    txSigner(overrides?: CallOverrides): Promise<[string]>;

    unblockUsers(
      users_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unclaimed(
      investor_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    unpauseSale(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vests(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  addVest(
    amounts_: PromiseOrValue<BigNumberish>[],
    tokens_: PromiseOrValue<BigNumberish>[],
    v_: PromiseOrValue<BigNumberish>,
    r_: PromiseOrValue<BytesLike>,
    s_: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  allowedPercentage(overrides?: CallOverrides): Promise<BigNumber>;

  alvara(overrides?: CallOverrides): Promise<string>;

  blockUsers(
    users_: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claim(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimAdmin(
    token_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimable(overrides?: CallOverrides): Promise<boolean>;

  claimed(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  fullPercent(overrides?: CallOverrides): Promise<BigNumber>;

  getAllInvestors(
    overrides?: CallOverrides
  ): Promise<AlvrTokenSale.InvestmentsStructOutput[]>;

  investorCnt(overrides?: CallOverrides): Promise<BigNumber>;

  investors(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  isBlocked(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  maximumTokens(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  minimumTokens(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  nonce(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  optionCnt(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  pauseSale(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  replaceUsers(
    oldUsers_: PromiseOrValue<string>[],
    newUsers_: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  schedules(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setAllowedPercentage(
    allowedPercentage_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAlvara(
    alvara_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setClaimable(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOptionCnt(
    optionCnt_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOptionMaxAmount(
    option: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOptionMinAmount(
    option: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOptionRange(
    option_: PromiseOrValue<BigNumberish>,
    minimum_: PromiseOrValue<BigNumberish>,
    maximum_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setSchedule(
    option_: PromiseOrValue<BigNumberish>,
    releases_: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTge(
    tge_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTreasuryWallet(
    treasuryWallet_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTxSigner(
    txSigner_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setUnclaimable(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tge(overrides?: CallOverrides): Promise<BigNumber>;

  timeMonth(overrides?: CallOverrides): Promise<BigNumber>;

  tokens(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalTokens(overrides?: CallOverrides): Promise<BigNumber>;

  totalVests(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  treasuryWallet(overrides?: CallOverrides): Promise<string>;

  txSigner(overrides?: CallOverrides): Promise<string>;

  unblockUsers(
    users_: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unclaimed(
    investor_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  unpauseSale(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vests(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    addVest(
      amounts_: PromiseOrValue<BigNumberish>[],
      tokens_: PromiseOrValue<BigNumberish>[],
      v_: PromiseOrValue<BigNumberish>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    allowedPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    alvara(overrides?: CallOverrides): Promise<string>;

    blockUsers(
      users_: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    claim(overrides?: CallOverrides): Promise<void>;

    claimAdmin(
      token_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimable(overrides?: CallOverrides): Promise<boolean>;

    claimed(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fullPercent(overrides?: CallOverrides): Promise<BigNumber>;

    getAllInvestors(
      overrides?: CallOverrides
    ): Promise<AlvrTokenSale.InvestmentsStructOutput[]>;

    investorCnt(overrides?: CallOverrides): Promise<BigNumber>;

    investors(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    isBlocked(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    maximumTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minimumTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    optionCnt(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    pauseSale(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    replaceUsers(
      oldUsers_: PromiseOrValue<string>[],
      newUsers_: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    schedules(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAllowedPercentage(
      allowedPercentage_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAlvara(
      alvara_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setClaimable(overrides?: CallOverrides): Promise<void>;

    setOptionCnt(
      optionCnt_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOptionMaxAmount(
      option: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOptionMinAmount(
      option: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOptionRange(
      option_: PromiseOrValue<BigNumberish>,
      minimum_: PromiseOrValue<BigNumberish>,
      maximum_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setSchedule(
      option_: PromiseOrValue<BigNumberish>,
      releases_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    setTge(
      tge_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTreasuryWallet(
      treasuryWallet_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTxSigner(
      txSigner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setUnclaimable(overrides?: CallOverrides): Promise<void>;

    tge(overrides?: CallOverrides): Promise<BigNumber>;

    timeMonth(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalTokens(overrides?: CallOverrides): Promise<BigNumber>;

    totalVests(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuryWallet(overrides?: CallOverrides): Promise<string>;

    txSigner(overrides?: CallOverrides): Promise<string>;

    unblockUsers(
      users_: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    unclaimed(
      investor_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpauseSale(overrides?: CallOverrides): Promise<void>;

    vests(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    addVest(
      amounts_: PromiseOrValue<BigNumberish>[],
      tokens_: PromiseOrValue<BigNumberish>[],
      v_: PromiseOrValue<BigNumberish>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    allowedPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    alvara(overrides?: CallOverrides): Promise<BigNumber>;

    blockUsers(
      users_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimAdmin(
      token_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimable(overrides?: CallOverrides): Promise<BigNumber>;

    claimed(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fullPercent(overrides?: CallOverrides): Promise<BigNumber>;

    getAllInvestors(overrides?: CallOverrides): Promise<BigNumber>;

    investorCnt(overrides?: CallOverrides): Promise<BigNumber>;

    investors(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isBlocked(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maximumTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minimumTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    optionCnt(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pauseSale(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    replaceUsers(
      oldUsers_: PromiseOrValue<string>[],
      newUsers_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    schedules(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAllowedPercentage(
      allowedPercentage_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAlvara(
      alvara_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setClaimable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOptionCnt(
      optionCnt_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOptionMaxAmount(
      option: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOptionMinAmount(
      option: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOptionRange(
      option_: PromiseOrValue<BigNumberish>,
      minimum_: PromiseOrValue<BigNumberish>,
      maximum_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setSchedule(
      option_: PromiseOrValue<BigNumberish>,
      releases_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTge(
      tge_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTreasuryWallet(
      treasuryWallet_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTxSigner(
      txSigner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setUnclaimable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tge(overrides?: CallOverrides): Promise<BigNumber>;

    timeMonth(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalTokens(overrides?: CallOverrides): Promise<BigNumber>;

    totalVests(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    treasuryWallet(overrides?: CallOverrides): Promise<BigNumber>;

    txSigner(overrides?: CallOverrides): Promise<BigNumber>;

    unblockUsers(
      users_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unclaimed(
      investor_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpauseSale(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vests(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addVest(
      amounts_: PromiseOrValue<BigNumberish>[],
      tokens_: PromiseOrValue<BigNumberish>[],
      v_: PromiseOrValue<BigNumberish>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    allowedPercentage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    alvara(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    blockUsers(
      users_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claim(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimAdmin(
      token_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimed(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fullPercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllInvestors(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    investorCnt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    investors(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isBlocked(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maximumTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minimumTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    optionCnt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pauseSale(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    replaceUsers(
      oldUsers_: PromiseOrValue<string>[],
      newUsers_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    schedules(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAllowedPercentage(
      allowedPercentage_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAlvara(
      alvara_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setClaimable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOptionCnt(
      optionCnt_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOptionMaxAmount(
      option: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOptionMinAmount(
      option: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOptionRange(
      option_: PromiseOrValue<BigNumberish>,
      minimum_: PromiseOrValue<BigNumberish>,
      maximum_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setSchedule(
      option_: PromiseOrValue<BigNumberish>,
      releases_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTge(
      tge_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTreasuryWallet(
      treasuryWallet_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTxSigner(
      txSigner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setUnclaimable(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    timeMonth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokens(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalVests(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    treasuryWallet(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    txSigner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unblockUsers(
      users_: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unclaimed(
      investor_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpauseSale(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vests(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
