import React from 'react';

import { Button, NextImage } from '@/components';
import UnstyledLink from '@/components/links/UnstyledLink';

import hives from '~/images/hives-3.png';

export default function Intro2() {
  return (
    <div className="container mx-auto flex flex-col items-end p-5 md:flex-row md:px-20 ">
      <section className="flex flex-col gap-[48px] md:w-1/2 ">
        <span className="bg-gradient-to-r from-purple-650 to-fuchsia-450 bg-clip-text text-transparent">
          ALVARA PROTOCOL
        </span>
        <h2 className="text-4xl font-medium uppercase tracking-wider">
          Marketplace
        </h2>
        <div className="h-[2px] w-full bg-gradient-to-r from-fuchsia-400 to-transparent"></div>
        <p className="w-4/5">
          The BTS Marketplace allows creators to auction ERC-BTS tokens for
          buyers to receive management rights and revenue.
          <br></br>
          <br></br>
          Additionally, holders of ERC-BTS tokens can earn a percentage of
          trading fees generated by their fund &apos; s BTS LP tokens. The
          marketplace provides comprehensive information about each fund, and
          sellers have full control over their auction listings.
        </p>
        <UnstyledLink href="http://discord.gg/pHDDF2MS8v">
          <Button
            variant="primary"
            className="max-w-max rounded-lg py-4 uppercase"
          >
            Join The Hive
          </Button>
        </UnstyledLink>
      </section>
      <div className="hidden md:block md:w-1/2">
        <NextImage
          className="m-auto"
          width={370}
          height={430}
          src={hives}
          alt="top-right-hives"
        />
      </div>
    </div>
  );
}
