import Link from 'next/link';
import React from 'react';

import { Button } from '@/components';
import UnstyledLink from '@/components/links/UnstyledLink';
import AppScreenImage from '@/components/Svg/AppScreenImage';

export default function Intro2() {
  return (
    <div className="container mx-auto flex flex-col items-end p-5 lg:flex-row  ">
      <section className="lg-w-1/2 flex flex-col gap-[48px] ">
        <span className="bg-gradient-to-r from-purple-650 to-fuchsia-450 bg-clip-text text-3xl text-transparent">
          ALVARA PROTOCOL
        </span>
        <div className="flex flex-col gap-3">
          <h1 className="text-4xl font-medium tracking-wider">Marketplace</h1>
          <div className="h-[2px] w-full bg-gradient-to-r from-fuchsia-400 to-transparent"></div>
        </div>
        <p className="w-4/5">
          The BTS Marketplace serves as a platform where creators can auction
          their ERC-BTS tokens. <br />
          <br />
          This unique feature paves the way for buyers to gain management rights
          and revenue.
          <br /> Moreover, holders of ERC-BTS tokens stand to benefit from a
          portion of the trading fees generated by their fund&apos;s BTS
          Liquidity Pool (LP) tokens via{' '}
          <Link href="/hivex">
            <a className=" underline">Alvara&apos;s HiveX.</a>
          </Link>
          <br />
          <br /> The marketplace presents a wealth of information on each fund,
          providing sellers with complete autonomy over their auction listings.
        </p>
        <UnstyledLink href="/market-place">
          <Button variant="primary" className="max-w-max rounded-lg py-4">
            Read More
          </Button>
        </UnstyledLink>
      </section>
      <div className=" lg-w-1/2 max-w-xl items-center justify-center   lg:min-w-[500px]">
        <AppScreenImage className="h-full w-full" />
      </div>
    </div>
  );
}
