import Image from 'next/image';
import React from 'react';

import { NextImage } from '@/components';

import { styles } from '@/styles';

export default function MacketPlace() {
  return (
    <div className=" container mx-auto  flex w-full flex-col gap-[26px] font-montserrat ">
      <div className=" flex flex-col items-start justify-between gap-[26px] rounded-lg border-[1px] border-solid border-gray-500 bg-[#0D0F23] px-10 py-2  md:flex-row">
        <div className="grid place-content-start gap-[26px] py-5 md:max-w-[50%]">
          <h1
            className={[
              'w-full text-left font-medium',
              styles.context_title,
            ].join(' ')}
          >
            Marketplace
          </h1>
          <p
            className={['w-full text-left font-poppins', styles.context].join(
              ' ',
            )}
          >
            Our platform provides a unique opportunity for both buyers and
            sellers in the Alvara community. The BTS Marketplace is where BTS
            creators can list their ERC-BTS tokens for auction.
          </p>
        </div>
        <NextImage
          // useSkeleton
          imgClassName=" w-2/4 h-[190px]"
          src="/images/home/chart.svg"
          width="300"
          height="200"
          alt="chart"
        />
      </div>
      <div className="grid grid-cols-1 flex-row gap-[26px] overflow-hidden md:grid-cols-2">
        <div className="flex flex-col items-start rounded-lg border-[1px] border-solid border-gray-500 bg-[#0D0F23]  bg-[100%_auto] bg-center bg-no-repeat py-10 pb-5 md:flex-row md:bg-[url('/images/home/button-bg.png')] ">
          <div className="flex flex-col gap-[28px]  px-10 md:w-3/4">
            <h1
              className={[
                'w-full text-left font-medium',
                styles.context_title,
              ].join(' ')}
            >
              Sell the rights to your fund
            </h1>
            <p
              className={['w-full text-left font-poppins', styles.context].join(
                ' ',
              )}
            >
              Creators can list their tokens for sale, giving management rights
              and revenue streams to the buyer, including a percentage of
              trading fees generated by their fund&apos;s BTS LP tokens.
            </p>
          </div>
          <div className="grid w-full items-end justify-end md:hidden">
            <Image
              src="/images/home/buttons.png"
              layout="fixed"
              width={250}
              height={170}
              alt="Pie"
            />
          </div>
        </div>
        <div className="flex flex-col items-center justify-start gap-[26px] rounded-lg border-[1px]  border-solid border-gray-500 bg-[url('/images/home/last-bg.png')] bg-cover bg-center bg-no-repeat px-10 py-7 md:flex-row md:bg-[#0D0F23]">
          <div className="flex flex-col gap-[26px] md:w-4/5">
            <h1
              className={[
                'w-full text-left font-medium',
                styles.context_title,
              ].join(' ')}
            >
              Clear data
            </h1>
            <p
              className={['w-full text-left font-poppins', styles.context].join(
                ' ',
              )}
            >
              Our marketplace provides clear and comprehensive information about
              each fund listed for sale. Buyers can easily view the profit/loss,
              decentralized (DAO) status, underlying assets, and annual
              management revenue stream for each fund.
            </p>{' '}
          </div>
          <div className="grid w-full items-center justify-stretch md:hidden">
            <Image
              className="w-full"
              src="/images/home/last.png"
              layout="fixed"
              width={300}
              height={170}
              alt="Pie"
            />
          </div>
        </div>
      </div>
    </div>
  );
}
